#!/usr/bin/ruby
require 'json'
require 'csv'

# Load the nouns.json file
file = JSON.parse(File.read('../nouns.json'))

# These are the headers that Weblate expects in the uploaded CSV
headers = "location,source,target,id,fuzzy,context,translator_comments,developer_comments"
# example = ",abelian category,abelian category,,FALSE,0ebe035f/0b0e02cd,,https://www.wikidata.org/wiki/Q318737"
# example = "","category","catégorie","","False","0ebe035f","féminin","https://www.wikidata.org/wiki/Q719395"

csv_data_EN = []

def generate_row (key, value, parent_key = nil, parent_value = nil)
  location = ''
  if parent_key.nil?
    source = value["root"]["EN"]["atom"]
  else
    case value["root"]["EN"]["pstn"]
    when 'before'
      source = value["root"]["EN"]["atom"] + ' ' + parent_value["root"]["EN"]["atom"]
    when 'after'
      source = parent_value["root"]["EN"]["atom"] + ' ' + value["root"]["EN"]["atom"]
    end
  end
  target = source
  id = ''
  fuzzy = 'FALSE'
  context = parent_key.nil? ? key : "#{parent_key}/#{key}"
  translator_comments = ''
  developer_comments = ''
  unless value["refs"]["wikidata"].nil?
    developer_comments = "https://www.wikidata.org/wiki/#{value["refs"]["wikidata"]}"
  end
  return [location,source,target,id,fuzzy,context,translator_comments,developer_comments]
end


file.each do |k,v|
  csv_data_EN.append(generate_row k, v)
  unless v["adjs"].nil?
    v["adjs"].each do |l,w|
      csv_data_EN.append(generate_row l, w, k, v)
    end
  end
end

File.write("weblate_EN.csv", csv_data_EN.map(&:to_csv).join)
