#!/usr/bin/ruby
require 'json'
require 'csv'

# Load the nouns.json file
file = JSON.parse(File.read('../nouns.json'))

# These are the headers that Weblate expects in the uploaded CSV
headers = "location,source,target,id,fuzzy,context,translator_comments,developer_comments"
# example = ",abelian category,abelian category,,FALSE,0ebe035f/0b0e02cd,,https://www.wikidata.org/wiki/Q318737"

csv_data = []

def generate_row (k, v, pre = nil)
  location = ''
  source = v["root"]["EN"]["atom"]
  target = v["root"]["EN"]["atom"]
  id = ''
  fuzzy = 'FALSE'
  context = pre.nil? ? k : "#{pre}/#{k}"
  translator_comments = ''
  developer_comments = ''
  unless v["refs"]["wikidata"].nil?
    developer_comments = "https://www.wikidata.org/wiki/#{v["refs"]["wikidata"]}"
  end
  return [location,source,target,id,fuzzy,context,translator_comments,developer_comments]
end


file.each do |k,v|
  csv_data.append(generate_row k, v)
  # TO-DO: fix adjectives
  #        you can't just use the same thing, because the string has to contain
  #        the root atom as well! i.e. you'll need to use "pstn"
  # unless v["adjs"].nil?
  #   v["adjs"].each do |l,w|
  #     csv_data.append(generate_row l, w, k)
  #   end
  # end
end

File.write("weblate_EN.csv", csv_data.map(&:to_csv).join)
