#!/usr/bin/ruby
require 'json'
require 'csv'

# Load the nouns.json file
file = JSON.parse(File.read('../nouns.json'))

# These are the headers that Weblate expects in the uploaded CSV
headers = "location,source,target,id,fuzzy,context,translator_comments,developer_comments"
# example = ",abelian category,abelian category,,FALSE,0ebe035f/0b0e02cd,,https://www.wikidata.org/wiki/Q318737"

csv_data = []

file.each do |k,v|
  location = ''
  source = v["root"]["EN"]["atom"]
  target = v["root"]["EN"]["atom"]
  id = ''
  fuzzy = 'FALSE'
  context = k
  translator_comments = ''
  developer_comments = ''
  unless v["refs"]["wikidata"].nil?
    developer_comments = "https://www.wikidata.org/wiki/#{v["refs"]["wikidata"]}"
  end
  csv_data.append([location,source,target,id,fuzzy,context,translator_comments,developer_comments])
end

File.write("weblate_EN.csv", csv_data.map(&:to_csv).join)
